version: '3.5'
services:

  bookmarks-db:
    image: postgres:12.3
    container_name: bookmarks-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bookmarks-api-nestjs:
    build:
      context: ../
      target: development
    command: npm run start:dev
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - bookmarks-db
    environment:
      DATABASE_HOST: bookmarks-db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: bookmarks
